### ISSUE TITLE
FOCUS grading transition

### ISSUE THREAD

**Issue by mca-it** [masonclassicalacademy/backlog#11]
## Background
There are impacts culturally with the switch and rigid nature of focus, especially in comparison to gradicus and the flexibility and convenience it offers. We will just need to keep the bigger picture in line - double work, impact to teachers and maintaining the culture. Some teachers or parents may have questions in regards to changes when course name changes appear, etc. to align to focus - and the state requirements. In the past we used to customize the course names and managed alignment of our custom course names to the state standards and scholarships as a way to communicate more effective and clearly with parents and teachers. Now with moving straight to focus on the grading, things like course names will have ripple impacts that may not be apparent to teachers or parents why changes are happening, as they won't have visibility to the backend system we now have to conform to. This is not a deal breaker to the shift, but we did an enormous amount on the backend to make our communications fit our culture and be more precise and clear to benefit parents and our educators.

Now the changes resulting from moving to focus will make this more difficult to customize at the top level like we currently do, and so we will be using defaults setup by the district/state which will not be as clear or precise or sensible even in some situations. It will definitely generate a reaction from a certain group of parents and educators as a result.

## Plan
The plan is to continue to fix past mistakes, mis entries, etc. so we have the accurate schedules and rosters resolved. Our data entry team is working many hours every day, as led and directed by Mr. Schmitt on making this right. It is a ton of work and cleanup, but it is working efficiently and moving us in the proper direction to make a smooth transition.

We will see larger impacts the next few weeks but will eventually 'catch up' with the current students. Dealing with the other topics of managing records from the past is out of scope for this effort. We will manage to that separately.

I think the changes are important to note and understand, because questions and reactions will be had, and we need to consider what type of context, communication and training is provided- especially to our educators. They might be confused, and the changes may even roll into curriculum changes eventually to accommodate to state standards. That is the broader concern I see tied to this.

Without going into the details on this, the one very clear example Mr. Schmitt gave was considering how Lit & Comp may eventually need to be combined. Understanding that example provides a good perspective on the magnitude of the changes as part of this transition.

Going forward, we need to make sure the training is more clear, direct, and simplistic. The last training that Kate gave was overwhelming it seems. It didn't go well, and it was because it wasn't simple enough and was all over the map. I should consider doing the training going forward -or at least be able to review the training prior to the event, so I can modify and keep things 'focused' (pun intended).

## Evaluation/Status
We are in a very good position and on-track. Most teachers are taking attendance effectively (minus outliers due to our own mistakes-which are being cleared up).

## Decisions/Impacts
For meeting the Q2 goal of teachers doing both attendance and grading we need to decide and be aware of the following items:

* Do we want educators inputting semester or yearly grading (according to Mr Schmitt). My assumption was we were moving to all grading, homework, etc.
* How much of the grading can we realistically transition - daily, weekly, quarterly, semesterly, yearly, etc.
* Do we all understand this is a more bottom-up decision to have the teachers doing the entry, administrators being able to review. Right now it seems more top-down cover by the administrators for the educators.

**Comment by mca-it** [comment]
A handful of people coming together to discuss in greater detail the plan for transition to using focus for grading. It isn't a technical issue, but more of a change management one. There are legitimate concerns around the impact to teachers and parents during a mid-year transition. 

So, we're getting several administrators and Mr. Hull together to walk through and to come up with a more concrete plan we can all agree to.

**Comment by masonclassicalacademy** [comment]
It appears there was a communication breakdown, since not everyone understood the expectations to move this year. Also #52
