### ISSUE TITLE
Surplus Equipment Disposal

### ISSUE THREAD

**Issue by mca-it** [masonclassicalacademy/backlog#16]
## Background
We have a lot of unused and possibly outdated IT equipment like desktop towers, monitors, mice, etc. From time-to-time we will need to dispose of this IT equipment in a way that makes sense.

## Considerations
Is there a way to "sell" to our staff/teachers/students?
Can we get a tax write-off for any of this?
Is there a free way to do this?
What guidelines do we have in place, responsibilities when discarding as a public school?

## Documentation
We will want to document this in with an ADR so it is clear for the rationale and why we did this.

**Comment by fsteer** [comment]
Completed.
