### ISSUE TITLE
password manager?

### ISSUE THREAD

**Issue by ghost** [masonclassicalacademy/backlog#31]
I want to understand if we have a password manager system setup for us or not.

If yes, then I want to document and move our login information into them and validate them, and then remove them from our documentation. If not, then I want to setup a vault or some type of password manager system for free. This makes sense given our size and number of passwords. It will also provide us a way to not store passwords in systems like Google Docs or Github.

**Comment by mca-it** [comment]
We do not currently have a password manager. I am recommeding we build or purchase a SaaS provider one to manage IT, HR, and Finance passwords in a more secure manner and remove them all from documentation, etc.
